- name: add helm chart repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: install CustomResourceDefinition resources
  ansible.builtin.command: kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v{{ cert_manager_version }}/cert-manager.crds.yaml
  environment:
    KUBECONFIG: /home/{{ ansible_user_id }}/.kube/config

- name: install
  kubernetes.core.helm:
    name: cert-manager
    release_state: present
    namespace: cert-manager
    chart_ref: jetstack/cert-manager
    chart_version: "{{ cert_manager_version }}"
    create_namespace: yes
    wait: yes
    values: "{{ lookup('template', 'values.yml.j2', variable_start_string='<<',  variable_end_string='>>') | from_yaml }}"
    update_repo_cache: yes
  environment:
    KUBECONFIG: /home/{{ ansible_user_id }}/.kube/config

- name: apply cluster issuer
  ansible.builtin.shell: "cat <<EOF | kubectl apply -f -\n {{ cluster_issuer }}\n EOF"
  vars:
    cluster_issuer: "{{ lookup('template', './cluster-issuer.yml.j2') }}"
  environment:
    KUBECONFIG: /home/{{ ansible_user_id }}/.kube/config
