- name: add helm chart repo
  kubernetes.core.helm_repository:
    name: hashicorp
    repo_url: https://helm.releases.hashicorp.com

- name: install
  kubernetes.core.helm:
    name: vault
    release_state: present
    namespace: vault
    chart_ref: hashicorp/vault
    chart_version: "{{ vault_version }}"
    create_namespace: yes
    wait: yes
    values: "{{ lookup('template', 'values.yml.j2', variable_start_string='<<',  variable_end_string='>>') | from_yaml }}"
    update_repo_cache: yes
  environment:
    KUBECONFIG: /home/{{ ansible_user_id }}/.kube/config

- name: apply vault certificate
  ansible.builtin.shell: "cat <<EOF | kubectl apply -f -\n {{ ca }}\n EOF"
  vars:
    ca: "{{ lookup('template', './certificate.yml.j2') }}"
  environment:
    KUBECONFIG: /home/{{ ansible_user_id }}/.kube/config
