- name: turn swap off
  become: yes
  ansible.builtin.shell: swapoff -a

- name: deploy k3s config file
  become: yes
  ansible.builtin.template:
    src: config.yml.j2
    dest: /k3s-config.yaml
    group: root
    owner: root
    mode: "0600"

- name: cluster init
  become: yes
  ansible.builtin.shell: curl -sfL https://get.k3s.io | K3S_CONFIG_FILE=/k3s-config.yaml sh -s - server

- name: install helm
  become: yes
  ansible.builtin.shell: curl {{ helm_download }} | bash

- name: create kube directory for user home
  ansible.builtin.file:
    path: /home/{{ ansible_user_id }}/.kube
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    state: directory

- name: export kube config to the users home
  become: yes
  ansible.builtin.shell: k3s kubectl config view --raw > /home/{{ ansible_user_id }}/.kube/config

- name: set correct kube config permissions
  become: yes
  ansible.builtin.file:
    path: /home/{{ ansible_user_id }}/.kube/config
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0600"

- name: add KUBECONFIG environment variable to users profile
  ansible.builtin.shell: "echo 'export KUBECONFIG=/home/{{ ansible_user_id }}/.kube/config' >> /home/{{ ansible_user_id }}/.profile"

- name: save the cluster joining token
  become: yes
  ansible.builtin.fetch:
    src: /var/lib/rancher/k3s/server/node-token
    dest: node-token.txt
    flat: true
