- name: add helm chart repo
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io

- name: install
  kubernetes.core.helm:
    name: longhorn
    release_state: present
    namespace: longhorn-system
    chart_ref: longhorn/longhorn
    chart_version: "{{ longhorn_version }}"
    create_namespace: yes
    wait: yes
    values: "{{ lookup('template', 'values.yml.j2', variable_start_string='<<',  variable_end_string='>>') | from_yaml }}"
    update_repo_cache: yes
  environment:
    KUBECONFIG: /home/{{ ansible_user_id }}/.kube/config
