- name: turn swap off
  become: yes
  ansible.builtin.shell: swapoff -a

- name: deploy k3s config file
  become: yes
  ansible.builtin.template:
    src: config.yml.j2
    dest: /k3s-config.yaml
    group: root
    owner: root
    mode: "0600"
  vars:
    k3s_token: "{{ lookup('file', 'node-token.txt') }}"

- name: agent init
  become: yes
  ansible.builtin.shell: curl -sfL https://get.k3s.io | K3S_CONFIG_FILE=/k3s-config.yaml sh -s - agent
