- name: turn swap off command line
  become: yes
  ansible.builtin.shell: swapoff -a

- name: remove swap.img from /etc/fstab
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: "^/swap.img"
    state: absent

- name: modprobe overlay
  become: yes
  community.general.modprobe:
    name: overlay
    state: present
  
- name: modprobe br_netfilter
  become: yes
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: allow ip forward
  become: yes
  ansible.builtin.shell: sysctl -w net.ipv4.ip_forward=1

- name: iptables bridged traffic
  become: yes
  ansible.builtin.shell: sysctl -w net.bridge.bridge-nf-call-iptables=1

- name: install kubelet, kubeadm, and kubectl
  become: yes
  ansible.builtin.apt:
    pkg:
      - "kubelet={{ kubernetes_version }}-00"
      - "kubeadm={{ kubernetes_version }}-00"
      - "kubectl={{ kubernetes_version }}-00"
    state: present
    update_cache: yes

- name: pull kubernetes images
  become: yes
  shell: kubeadm config images pull
