- name: install prereq apt packages
  become: yes
  ansible.builtin.apt:
    state: present
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: make keyrings directory
  ansible.builtin.file:
    state: directory
    path: /etc/apt/keyrings

- name: add docker repo GPG key
  become: yes
  ansible.builtin.shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --yes --dearmor -o /etc/apt/keyrings/docker.gpg

- name: add docker repository
  become: yes
  ansible.builtin.shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: add kubernetes repo GPG key
  become: yes
  ansible.builtin.shell: curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: add Kubernetes repository
  become: yes
  ansible.builtin.shell: echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
