- name: join worker to cluster
  become: yes
  ansible.builtin.shell: "{{ joining_command }}"
  vars:
    joining_command: "{{ lookup('file', 'node-token.txt') }}"
  when: inventory_hostname not in groups["control-planes"]

- name: join control-plane to cluster
  become: yes
  ansible.builtin.shell: "{{ joining_command }} --control-plane --certificate-key {{ certificate_key }} --apiserver-advertise-address {{ node_ip }}"
  vars:
    joining_command: "{{ lookup('file', 'node-token.txt') }}"
  when: inventory_hostname in groups["control-planes"]
